# This compose file is useful for testing https.
# The .env file sets ENVVARS for the Docker CLI used by this compose file.
---
version: "3"
services:
  dash_2_demo:
    build: .
    ports:
      - 8050:8050
    container_name: dash_2_demo
    command: [ "gunicorn", "-b", ":8050", "app:server" ]
